export const routes = {
  electricalWorkshop: 'department/electrical_workshop',
  reactorFactory: 'department/reactor_factory',
  turbineFactory: 'department/turbine_factory',
  zachFactory: 'department/zach_factory',
  production: 'department/production',
  history: 'department/history',
  safety: 'department/safety',
  cooperation: 'cooperation',
  vacancies: 'vacancies',
  education: 'education',
  structure: 'structure',
  contacts: 'contacts',
  shopping: 'shopping',
  events: 'events',
  report: 'report',
  news: 'news',
  home: '/',
};
