export const routes = {
  electricalWorkshop: 'electrical_workshop',
  reactorFactory: 'reactor_factory',
  turbineFactory: 'turbine_factory',
  zachFactory: 'zach_factory',
  cooperation: 'cooperation',
  production: 'production',
  vacancies: 'vacancies',
  education: 'education',
  structure: 'structure',
  contacts: 'contacts',
  shopping: 'shopping',
  history: 'history',
  safety: 'safety',
  events: 'events',
  report: 'report',
  news: 'news',
  home: '/',
};
